[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_APP_VERSION = "1.0.0"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# These redirects are handled by Next.js internally
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-entry-point"
  status = 200
  force = true
